// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/proto/service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_3474577474948ca0, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Message struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	RoomId               string   `protobuf:"bytes,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
	RoomName             string   `protobuf:"bytes,4,opt,name=roomName,proto3" json:"roomName,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp            string   `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_3474577474948ca0, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Message) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Message) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *Message) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Message) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type Room struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatorId            string   `protobuf:"bytes,3,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_3474577474948ca0, []int{2}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Room) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Room) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

type CreateOrDelRoom struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	RoomName             string   `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrDelRoom) Reset()         { *m = CreateOrDelRoom{} }
func (m *CreateOrDelRoom) String() string { return proto.CompactTextString(m) }
func (*CreateOrDelRoom) ProtoMessage()    {}
func (*CreateOrDelRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_3474577474948ca0, []int{3}
}

func (m *CreateOrDelRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrDelRoom.Unmarshal(m, b)
}
func (m *CreateOrDelRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrDelRoom.Marshal(b, m, deterministic)
}
func (m *CreateOrDelRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrDelRoom.Merge(m, src)
}
func (m *CreateOrDelRoom) XXX_Size() int {
	return xxx_messageInfo_CreateOrDelRoom.Size(m)
}
func (m *CreateOrDelRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrDelRoom.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrDelRoom proto.InternalMessageInfo

func (m *CreateOrDelRoom) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateOrDelRoom) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

type Connect struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	RoomName             string   `protobuf:"bytes,3,opt,name=roomName,proto3" json:"roomName,omitempty"`
	Active               bool     `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connect) Reset()         { *m = Connect{} }
func (m *Connect) String() string { return proto.CompactTextString(m) }
func (*Connect) ProtoMessage()    {}
func (*Connect) Descriptor() ([]byte, []int) {
	return fileDescriptor_3474577474948ca0, []int{4}
}

func (m *Connect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connect.Unmarshal(m, b)
}
func (m *Connect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connect.Marshal(b, m, deterministic)
}
func (m *Connect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connect.Merge(m, src)
}
func (m *Connect) XXX_Size() int {
	return xxx_messageInfo_Connect.Size(m)
}
func (m *Connect) XXX_DiscardUnknown() {
	xxx_messageInfo_Connect.DiscardUnknown(m)
}

var xxx_messageInfo_Connect proto.InternalMessageInfo

func (m *Connect) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Connect) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *Connect) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type ListRoom struct {
	Rooms                []*Room  `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRoom) Reset()         { *m = ListRoom{} }
func (m *ListRoom) String() string { return proto.CompactTextString(m) }
func (*ListRoom) ProtoMessage()    {}
func (*ListRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_3474577474948ca0, []int{5}
}

func (m *ListRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRoom.Unmarshal(m, b)
}
func (m *ListRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRoom.Marshal(b, m, deterministic)
}
func (m *ListRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRoom.Merge(m, src)
}
func (m *ListRoom) XXX_Size() int {
	return xxx_messageInfo_ListRoom.Size(m)
}
func (m *ListRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ListRoom proto.InternalMessageInfo

func (m *ListRoom) GetRooms() []*Room {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_3474577474948ca0, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*Message)(nil), "proto.Message")
	proto.RegisterType((*Room)(nil), "proto.Room")
	proto.RegisterType((*CreateOrDelRoom)(nil), "proto.CreateOrDelRoom")
	proto.RegisterType((*Connect)(nil), "proto.Connect")
	proto.RegisterType((*ListRoom)(nil), "proto.ListRoom")
	proto.RegisterType((*Empty)(nil), "proto.Empty")
}

func init() { proto.RegisterFile("internal/proto/service.proto", fileDescriptor_3474577474948ca0) }

var fileDescriptor_3474577474948ca0 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xdb, 0xca, 0xd3, 0x40,
	0x14, 0x85, 0x49, 0x9a, 0x43, 0xbb, 0x53, 0x5b, 0x18, 0xa4, 0x84, 0x50, 0xb0, 0xe6, 0x4a, 0x3c,
	0xb4, 0xa5, 0xf6, 0x05, 0x34, 0x15, 0x2d, 0x68, 0x85, 0x88, 0xb7, 0xc2, 0x98, 0x6c, 0x34, 0x90,
	0x64, 0xca, 0xcc, 0x58, 0xf1, 0x91, 0x7c, 0x03, 0x1f, 0x4f, 0xe6, 0x90, 0xb6, 0x29, 0x28, 0xff,
	0x7f, 0xd5, 0xf9, 0x66, 0x75, 0xad, 0xd9, 0x7b, 0x05, 0xe6, 0x55, 0x2b, 0x91, 0xb7, 0xb4, 0x5e,
	0x1d, 0x39, 0x93, 0x6c, 0x25, 0x90, 0x9f, 0xaa, 0x02, 0x97, 0x9a, 0x88, 0xaf, 0x7f, 0xd2, 0xa7,
	0xe0, 0x7d, 0x16, 0xc8, 0xc9, 0x04, 0xdc, 0xaa, 0x8c, 0x9d, 0x85, 0xf3, 0x64, 0x94, 0xbb, 0x55,
	0x49, 0x08, 0x78, 0x2d, 0x6d, 0x30, 0x76, 0xf5, 0x8d, 0x3e, 0xa7, 0xbf, 0x1d, 0x08, 0x3f, 0xa0,
	0x10, 0xf4, 0x1b, 0x92, 0x19, 0x04, 0x3f, 0x04, 0xf2, 0x7d, 0xe7, 0xb1, 0x44, 0x12, 0x18, 0xaa,
	0xd3, 0xe1, 0xe2, 0x3d, 0xb3, 0xf2, 0x70, 0xc6, 0x9a, 0x7d, 0x19, 0x0f, 0x8c, 0xc7, 0x90, 0xf2,
	0xa8, 0x93, 0xf6, 0x78, 0xc6, 0xd3, 0x31, 0x89, 0x21, 0x2c, 0x58, 0x2b, 0xb1, 0x95, 0xb1, 0xaf,
	0xa5, 0x0e, 0xc9, 0x1c, 0x46, 0xb2, 0x6a, 0x50, 0x48, 0xda, 0x1c, 0xe3, 0x40, 0x6b, 0x97, 0x8b,
	0xf4, 0x1d, 0x78, 0x39, 0x63, 0xcd, 0x5d, 0xf6, 0x52, 0x49, 0x05, 0x47, 0x2a, 0x19, 0x3f, 0x8f,
	0x76, 0xb9, 0x48, 0x0f, 0x30, 0xcd, 0x14, 0xe0, 0x47, 0xbe, 0xc3, 0x5a, 0x87, 0x3e, 0x02, 0x4f,
	0x2d, 0xa5, 0x63, 0xa3, 0x4d, 0x64, 0x1a, 0x5d, 0xaa, 0x1e, 0x73, 0x2d, 0xf4, 0x36, 0x72, 0xfb,
	0x1b, 0xa5, 0x5f, 0x20, 0xcc, 0x58, 0xdb, 0x62, 0x21, 0xef, 0x97, 0x33, 0xb8, 0x69, 0x66, 0x06,
	0x01, 0x2d, 0x64, 0x75, 0x32, 0x9d, 0x0d, 0x73, 0x4b, 0xe9, 0x0b, 0x18, 0xbe, 0xaf, 0x84, 0xd4,
	0x83, 0x3e, 0x06, 0x5f, 0xfd, 0x5f, 0xc4, 0xce, 0x62, 0x70, 0xf5, 0x82, 0xd2, 0x72, 0xa3, 0xa4,
	0x21, 0xf8, 0x6f, 0x9a, 0xa3, 0xfc, 0xb5, 0xf9, 0xe3, 0xc2, 0x28, 0xfb, 0x4e, 0xb5, 0x51, 0x90,
	0x2d, 0x3c, 0x7c, 0xcd, 0x19, 0x2d, 0x0b, 0x6a, 0xa2, 0xba, 0xef, 0x3e, 0xb1, 0x11, 0x96, 0x93,
	0xb1, 0x65, 0x9d, 0x41, 0xb6, 0xf0, 0xc0, 0x74, 0x75, 0xc0, 0x9f, 0x7a, 0x80, 0x99, 0x95, 0x6f,
	0x1a, 0x4c, 0xae, 0x27, 0x21, 0x6b, 0x18, 0x1b, 0xfd, 0x93, 0xe4, 0x48, 0x9b, 0xf3, 0x1b, 0xb6,
	0xa6, 0xe4, 0xe6, 0xcd, 0xb5, 0x43, 0x9e, 0x41, 0x94, 0xd5, 0x4c, 0xfc, 0xcb, 0xd0, 0x1f, 0x6a,
	0x03, 0xb0, 0xc3, 0x1a, 0x25, 0xfe, 0x77, 0xa2, 0xbe, 0xe7, 0x39, 0x44, 0x6f, 0x51, 0xbe, 0xaa,
	0x6b, 0xd3, 0x46, 0x4f, 0x4c, 0xa6, 0x96, 0xba, 0x9a, 0xbf, 0x06, 0x9a, 0x5f, 0xfe, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0x3b, 0x24, 0x71, 0x16, 0x72, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatRoomsClient is the client API for ChatRooms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatRoomsClient interface {
	BroadcastRoomMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error)
	CreateNewRoom(ctx context.Context, in *CreateOrDelRoom, opts ...grpc.CallOption) (*Room, error)
	CreateStream(ctx context.Context, in *Connect, opts ...grpc.CallOption) (ChatRooms_CreateStreamClient, error)
	CloseStream(ctx context.Context, in *Connect, opts ...grpc.CallOption) (*Empty, error)
	DeleteRoom(ctx context.Context, in *CreateOrDelRoom, opts ...grpc.CallOption) (*Empty, error)
	GetAllRooms(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListRoom, error)
}

type chatRoomsClient struct {
	cc *grpc.ClientConn
}

func NewChatRoomsClient(cc *grpc.ClientConn) ChatRoomsClient {
	return &chatRoomsClient{cc}
}

func (c *chatRoomsClient) BroadcastRoomMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.ChatRooms/BroadcastRoomMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatRoomsClient) CreateNewRoom(ctx context.Context, in *CreateOrDelRoom, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/proto.ChatRooms/CreateNewRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatRoomsClient) CreateStream(ctx context.Context, in *Connect, opts ...grpc.CallOption) (ChatRooms_CreateStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChatRooms_serviceDesc.Streams[0], "/proto.ChatRooms/CreateStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatRoomsCreateStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatRooms_CreateStreamClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type chatRoomsCreateStreamClient struct {
	grpc.ClientStream
}

func (x *chatRoomsCreateStreamClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatRoomsClient) CloseStream(ctx context.Context, in *Connect, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.ChatRooms/CloseStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatRoomsClient) DeleteRoom(ctx context.Context, in *CreateOrDelRoom, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.ChatRooms/DeleteRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatRoomsClient) GetAllRooms(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListRoom, error) {
	out := new(ListRoom)
	err := c.cc.Invoke(ctx, "/proto.ChatRooms/GetAllRooms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatRoomsServer is the server API for ChatRooms service.
type ChatRoomsServer interface {
	BroadcastRoomMessage(context.Context, *Message) (*Empty, error)
	CreateNewRoom(context.Context, *CreateOrDelRoom) (*Room, error)
	CreateStream(*Connect, ChatRooms_CreateStreamServer) error
	CloseStream(context.Context, *Connect) (*Empty, error)
	DeleteRoom(context.Context, *CreateOrDelRoom) (*Empty, error)
	GetAllRooms(context.Context, *Empty) (*ListRoom, error)
}

// UnimplementedChatRoomsServer can be embedded to have forward compatible implementations.
type UnimplementedChatRoomsServer struct {
}

func (*UnimplementedChatRoomsServer) BroadcastRoomMessage(ctx context.Context, req *Message) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastRoomMessage not implemented")
}
func (*UnimplementedChatRoomsServer) CreateNewRoom(ctx context.Context, req *CreateOrDelRoom) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewRoom not implemented")
}
func (*UnimplementedChatRoomsServer) CreateStream(req *Connect, srv ChatRooms_CreateStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateStream not implemented")
}
func (*UnimplementedChatRoomsServer) CloseStream(ctx context.Context, req *Connect) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseStream not implemented")
}
func (*UnimplementedChatRoomsServer) DeleteRoom(ctx context.Context, req *CreateOrDelRoom) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRoom not implemented")
}
func (*UnimplementedChatRoomsServer) GetAllRooms(ctx context.Context, req *Empty) (*ListRoom, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRooms not implemented")
}

func RegisterChatRoomsServer(s *grpc.Server, srv ChatRoomsServer) {
	s.RegisterService(&_ChatRooms_serviceDesc, srv)
}

func _ChatRooms_BroadcastRoomMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatRoomsServer).BroadcastRoomMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ChatRooms/BroadcastRoomMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatRoomsServer).BroadcastRoomMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatRooms_CreateNewRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrDelRoom)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatRoomsServer).CreateNewRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ChatRooms/CreateNewRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatRoomsServer).CreateNewRoom(ctx, req.(*CreateOrDelRoom))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatRooms_CreateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Connect)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatRoomsServer).CreateStream(m, &chatRoomsCreateStreamServer{stream})
}

type ChatRooms_CreateStreamServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type chatRoomsCreateStreamServer struct {
	grpc.ServerStream
}

func (x *chatRoomsCreateStreamServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _ChatRooms_CloseStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Connect)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatRoomsServer).CloseStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ChatRooms/CloseStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatRoomsServer).CloseStream(ctx, req.(*Connect))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatRooms_DeleteRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrDelRoom)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatRoomsServer).DeleteRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ChatRooms/DeleteRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatRoomsServer).DeleteRoom(ctx, req.(*CreateOrDelRoom))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatRooms_GetAllRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatRoomsServer).GetAllRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ChatRooms/GetAllRooms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatRoomsServer).GetAllRooms(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatRooms_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ChatRooms",
	HandlerType: (*ChatRoomsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BroadcastRoomMessage",
			Handler:    _ChatRooms_BroadcastRoomMessage_Handler,
		},
		{
			MethodName: "CreateNewRoom",
			Handler:    _ChatRooms_CreateNewRoom_Handler,
		},
		{
			MethodName: "CloseStream",
			Handler:    _ChatRooms_CloseStream_Handler,
		},
		{
			MethodName: "DeleteRoom",
			Handler:    _ChatRooms_DeleteRoom_Handler,
		},
		{
			MethodName: "GetAllRooms",
			Handler:    _ChatRooms_GetAllRooms_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateStream",
			Handler:       _ChatRooms_CreateStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/proto/service.proto",
}
